package com.datalens.app.ui.theme

import androidx.compose.ui.graphics.Color

// Indigo-based Material 3 scheme (fallback when dynamic color is unavailable).
val LightPrimary = Color(0xFF4459A9)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDCE1FF)
val LightOnPrimaryContainer = Color(0xFF001159)
val LightSecondary = Color(0xFF595D72)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDEE1F9)
val LightOnSecondaryContainer = Color(0xFF161B2C)
val LightTertiary = Color(0xFF75546F)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFD7F1)
val LightOnTertiaryContainer = Color(0xFF2C1229)
val LightBackground = Color(0xFFFBF8FF)
val LightOnBackground = Color(0xFF1A1B23)
val LightSurface = Color(0xFFFBF8FF)
val LightOnSurface = Color(0xFF1A1B23)
val LightSurfaceVariant = Color(0xFFE2E1EC)
val LightOnSurfaceVariant = Color(0xFF45464F)
val LightOutline = Color(0xFF767680)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

val DarkPrimary = Color(0xFFB3C4FF)
val DarkOnPrimary = Color(0xFF002A78)
val DarkPrimaryContainer = Color(0xFF2A4090)
val DarkOnPrimaryContainer = Color(0xFFDCE1FF)
val DarkSecondary = Color(0xFFC2C5DD)
val DarkOnSecondary = Color(0xFF2B3042)
val DarkSecondaryContainer = Color(0xFF414659)
val DarkOnSecondaryContainer = Color(0xFFDEE1F9)
val DarkTertiary = Color(0xFFE4BAD7)
val DarkOnTertiary = Color(0xFF44263E)
val DarkTertiaryContainer = Color(0xFF5C3A57)
val DarkOnTertiaryContainer = Color(0xFFFFD7F1)
val DarkBackground = Color(0xFF121318)
val DarkOnBackground = Color(0xFFE3E1E9)
val DarkSurface = Color(0xFF121318)
val DarkOnSurface = Color(0xFFE3E1E9)
val DarkSurfaceVariant = Color(0xFF45464F)
val DarkOnSurfaceVariant = Color(0xFFC6C5D0)
val DarkOutline = Color(0xFF8F909A)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
